### PR TITLE
style: add semantic release badge

### PR DESCRIPTION
**Pull request by jeremylgn**
self explanatory.

### CODE REVIEW

**Comment by ccamel** [comment]
@jeremylgn Use `docs: ...` for the prefix of your commit message as as the change pertains to documentation (`README.md`). Thanks :pray:

**Comment by jeremylgn** [comment]
> @jeremylgn Use `docs: ...` for the prefix of your commit message as as the change pertains to documentation (`README.md`). Thanks 🙏

Done :heavy_check_mark:

**Review by ccamel — APPROVED** [review]
Good! Thx :+1:

**Review by bdeneux — APPROVED** [review]
👍

**Pull request merged**
