### PR TITLE
Feat/objectarium compression

### PR DESCRIPTION
**Pull request by ccamel**
This PR addresses #192, which enables the support of compression of objects, through the [Snappy](https://en.wikipedia.org/wiki/Snappy_(compression)) compression algorithm as the primary supported algorithm.

The implementation introduces a design for the smart contract interface that enables the expression of object compression and control over the supported algorithms in a given bucket. This development paves the way for experimentation that will provide insights into the gas consumption associated with object storage in various contexts (cf. #191).

### CODE REVIEW

**Review by bdeneux — APPROVED** [review]
Nice, that seems good ! Thanks.

I'm just open a discussion about limits of bucket. I'm wondering about the `max_object_size` and `max_total_size` limits attributes that is related to the size of the uncompressed object.
Is it relevant to limit the total max size on uncompressed objects size ? Maybe on the size of one object could be useful but for the total bucket size I will use the compressed size to check limits.

**Comment by ccamel** [comment]
> I'm just open a discussion about limits of bucket. I'm wondering about the `max_object_size` and `max_total_size` limits attributes that is related to the size of the uncompressed object. Is it relevant to limit the total max size on uncompressed objects size ? Maybe on the size of one object could be useful but for the total bucket size I will use the compressed size to check limits (by changing limits attribute name `max_compressed_total_size` or adding a new limits attributes or just add a comment on this attribute documentation)

@bdeneux ah, yes it's a good point, and I had wondered about it. I am quite divided on the question. 🤔 Let's just say that from what I see of compressed volumes usually, the limits apply on the uncompressed data because through the volume, the files are seen for their actual size, and that's the approach I've taken. Also, limiting the total size by compressed size requires compressing first, which is costly (in gas) if the resulting size turns out to be unfortunatly larger than the limit.
However, I can understand that calculating on the uncompressed size does not make much sense in our case.
In any case, it is important to clarify this point as you have pointed out.

@amimart your thoughts?

**Review by amimart — APPROVED** [review]
Looks good to me! 😉

**Comment by ccamel** [comment]
Thanks for the review guys. :+1:

**Pull request merged**
